version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
      - image: redis:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm i
      - run: npm run bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      # Setup cc-test-reporter
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: export GIT_COMMIT_SHA=$CIRCLE_SHA1
      - run: export GIT_BRANCH=$CIRCLE_BRANCH
      
      - run: ./cc-test-reporter before-build
      - run: npm test
      - run: ./cc-test-reporter after-build --coverage-input-type lcov