export const BULL_MODULE_SERVICE = "BULL_MODULE_SERVICE";
export const BULL_MODULE_OPTIONS = "BULL_MODULE_OPTIONS";

export const BULL_QUEUE_DECORATOR = "BULL_QUEUE_DECORATOR";

export const BULL_WORKER_DECORATOR = "BULL_WORKER_DECORATOR";
export const BULL_WORKER_PROCESSOR_DECORATOR = "BULL_WORKER_PROCESSOR_DECORATOR";
export const BULL_QUEUE_EVENTS_DECORATOR = "BULL_QUEUE_EVENTS_DECORATOR";
export const BULL_QUEUE_EVENTS_PROCESSOR_DECORATOR = "BULL_QUEUE_EVENTS_PROCESSOR_DECORATOR";
