name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:lts
      env:
        REDIS_HOST: ${{ jobs.services.redis.ports['6379'] }}
    services: 
      redis:
        image: redis
        ports: 
          - "6379:6379"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: check host
        run: echo $REDIS_HOST
      # - name: Install npm packages
      #   run: npm ci
      # - name: Bootstrap monorepo packages
      #   run: npm run bootstrap
      # - name: Test monorepo packages
      #   run: npm test

      
