name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    services: 
      redis:
        image: redis
        ports: 
          - 6379/tcp
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install npm packages
        run: npm install
      - name: Bootstrap monorepo packages
        run: npm run bootstrap
      - name: Test monorepo packages
        run: npm test

      
