name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:lts
      env:
        REDIS_HOST: redis
        GIT_COMMIT_SHA: ${GITHUB_SHA}
        GIT_BRANCH: ${GITHUB_REF}
    services: 
      redis:
        image: redis
        ports: 
          - "6379:6379"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install npm packages
        run: npm ci
      - name: Bootstrap monorepo packages
        run: |
          npm run bootstrap
          npm run build
      - name: Setup cc-test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test monorepo packages
        run: | 
          npm test
          npx ts-node scripts/merge-coverage.ts
      - name: Report coverage
        run: ./cc-test-reporter after-build --coverage-input-type lcov

      
