name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: [10, 12]
    name: Test Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}
      env:
        REDIS_HOST: redis
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install npm packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Setup cc-test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test monorepo packages
        run: |
          npm test
          npx ts-node scripts/merge-coverage.ts
      - name: Report coverage
        run: ./cc-test-reporter after-build -r ${{ secrets.CC_TEST_REPORTER_ID }} --coverage-input-type lcov
