name: CI

on: [push]

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: anchan828

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up docker-compose
        run: docker-compose up -d
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
