name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Set up docker-compose
        run: docker-compose up -d
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: Install npm packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          debug: true
