name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: [12, 13]
    name: Test Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}
      env:
        REDIS_HOST: redis
        REDIS_PORT: 6379
    services:
      redis:
        image: redis
        ports:
          - "6379:6379"
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install npm packages
        run: npm ci
      - name: Bootstrap monorepo packages
        run: |
          npm run bootstrap
          npm run build
      - name: Lint
        run: npm run lint
      - name: Test monorepo packages
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          debug: true
