name: Weekly Release

on:
  schedule:
    - cron: "16 13 * * 3"
      branches:
        - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@master
      - name: Checkout master
        run: git checkout master
      - name: Install npm packages
        run: npm ci
      - name: Bootstrap monorepo packages
        run: |
          npm run bootstrap
          npm run build
      - name: Publish monorepo packages
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          git config --global user.email "${USERNAME}@gmail.com"
          git config --global user.name "${USERNAME}"
          git remote set-url origin "https://${USERNAME}:${GITHUB_TOKEN}@github.com/${USERNAME}/${REPOSITORY}.git"
          npm run publish
        env:
          USERNAME: anchan828
          REPOSITORY: nest-bull
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}