name: Weekly Release

on:
  schedule:
    - cron: "31 11 * * 3"
      branches:
        - master

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - uses: actions/checkout@master
      - name: Checkout master
        run: git checkout master
      - name: Install npm packages
        run: npm ci
      - name: Bootstrap monorepo packages
        run: |
          npm run bootstrap
          npm run build
      - name: Publish monorepo packages
        run: |
          echo "//registry.npmjs.org/:_authtoken=$NPM_TOKEN" >> ~/.npmrc
          git config --global user.email "anchan828@gmail.com"
          git config --global user.name "anchan828"
          npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}